default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: deremate_development_2
  username: desafio
  password: password

test:
  <<: *default
  database: deremate_test_2
  username: desafio
  password: password

production:
  <<: *default
  database: deremate_production_2
  username: deremate2
  password: <%= ENV['DEREMATE_DATABASE_PASSWORD'] %>
